sudo: required
services: 
  - docker

before_install:
  - docker build -t mytest -f Dockerfile.dev .

script:
  - docker run mytest npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: docket-test
  env: DocketTest-env
  bucket_name: elasticbeanstalk-us-east-1-757048572141
  bucket_path: "docket-test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  